[package]
name = "rcm-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
thiserror = "1.0.30"

[target.'cfg(target_os = "linux")'.dependencies]
glob = "0.3.0"
nix = "0.24.1"
