name: CD

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin

      - name: Test
        run: cargo test --release

      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin

      - name: Make DMG
        run: |
          make dmg-universal
          mv target/release/osx/Switcheroo.dmg Switcheroo-${{ github.ref_name }}_universal.dmg

      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}_universal.dmg $GITHUB_TOKEN

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: cargo test --release

      - name: Build
        run: cargo build --release

      - name: Upload portable executable
        run: |
          cp ./target/release/switcheroo.exe ./Switcheroo-${{ github.ref_name }}-portable_amd64.exe
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}-portable_amd64.exe $GITHUB_TOKEN
      - name: Install WiX
        run: nuget install WiX

      - name: Crate msi installer
        run: |
          ./WiX.*/tools/candle.exe -nologo -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./switcheroo.wixobj" "extra/windows/wix/switcheroo.wxs"
          ./WiX.*/tools/light.exe -nologo -ext WixUIExtension -ext WixUtilExtension \
            -out "./Switcheroo-${{ github.ref_name }}-installer_amd64.msi" -sice:ICE61 -sice:ICE91 \
            "./switcheroo.wixobj"

      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}-installer_amd64.msi $GITHUB_TOKEN

  linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Install ARM target
        run: rustup update && rustup target add aarch64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev binutils-aarch64-linux-gnu patchelf
      - name: Install cargo deb
        run: cargo install cargo-deb

      - name: Install cross
        run: cargo install cross

      - name: Create amd64 deb package
        run: |
          cargo deb --output Switcheroo-${{ github.ref_name }}_amd64.deb
      - name: Upload amd64 deb
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}_amd64.deb $GITHUB_TOKEN

      - name: Create arm64 release build
        run: |
          cross build --release --target aarch64-unknown-linux-gnu

      - name: Create arm64 deb package
        run: |
          cargo deb --output Switcheroo-${{ github.ref_name }}_arm64.deb --no-build
      - name: Upload arm64 deb
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}_arm64.deb $GITHUB_TOKEN

      - name: Install AppImage dependencies
        run: |
          pip install appimage-builder
      - name: Create AppImage
        run: |
          ./create_appimage.sh
          mv Switcheroo*.AppImage Switcheroo-${{ github.ref_name }}_amd64.AppImage
        continue-on-error: true

      - name: Upload amd64 AppImage
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Switcheroo-${{ github.ref_name }}_amd64.AppImage $GITHUB_TOKEN
        continue-on-error: true
